{{- if or .Values.config.create .Values.adminToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marathon-shepherd.fullname" . }}
  labels:
    {{- include "marathon-shepherd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.create }}
  {{ .Values.config.key }}: |
    {{- .Values.config.content | nindent 4 }}
  {{- end }}
  {{- if .Values.adminToken.value }}
  {{ .Values.adminToken.key }}: {{ .Values.adminToken.value | quote }}
  {{- end }}
{{- end }}
