{{- if and .Values.secret.value (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shepherd-adapter.fullname" . }}
  labels:
    {{- include "shepherd-adapter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.key }}: {{ .Values.secret.value | quote }}
{{- end }}
